#!/bin/sh
#
# Pre-Squish a CM otapackage for distribution
# cyanogen / Droid2
#

echo "CH package:"
CM_VARIANT=ch
if [ -f $ANDROID_BUILD_TOP/device/moto/droid2/releasetools/squisher ]; then
        . $ANDROID_BUILD_TOP/device/moto/droid2/releasetools/squisher
fi

echo "EU package:"
CM_VARIANT=eu
if [ -f $ANDROID_BUILD_TOP/device/moto/droid2/releasetools/squisher ]; then
        . $ANDROID_BUILD_TOP/device/moto/droid2/releasetools/squisher
fi

exit 0
