#!/bin/sh
#
# Pre-Squish a CM otapackage for distribution
# cyanogen / Milestone2 / Droid2
#

echo "US package:"
CM_VARIANT=us
if [ -f $ANDROID_BUILD_TOP/device/moto/droid2/releasetools/squisher ]; then
        . $ANDROID_BUILD_TOP/device/moto/droid2/releasetools/squisher
fi
